import type { Frame } from "./types";

/**
 * 테 카탈로그(데모 데이터).
 *
 * 실제 서비스에서는 제휴 매장/유통사 카탈로그를 붙이면 되고,
 * 추천 로직이 쓰는 필드(모양·사이즈·코받침·무게)만 채워지면 그대로 동작한다.
 * 사이즈는 안경테에 실제로 각인되는 규격(렌즈폭-브릿지-템플)을 따른다.
 */
export const FRAMES: Frame[] = [
  {
    id: "f-wel-01",
    name: "다온 웰링턴",
    brand: "DAON",
    shape: "wellington",
    rim: "full",
    material: "아세테이트",
    lensWidth: 50,
    bridge: 20,
    lensHeight: 42,
    temple: 145,
    totalWidth: 138,
    weightGram: 24,
    asianFit: true,
    adjustableNosePad: false,
    colors: ["블랙", "하바나", "클리어 그레이"],
    price: 128000,
    tags: ["기본템", "누진 가능", "도수 커버"],
  },
  {
    id: "f-bos-01",
    name: "무이 보스턴",
    brand: "MUI",
    shape: "boston",
    rim: "full",
    material: "아세테이트",
    lensWidth: 48,
    bridge: 21,
    lensHeight: 44,
    temple: 145,
    totalWidth: 136,
    weightGram: 22,
    asianFit: true,
    adjustableNosePad: true,
    colors: ["브라운 데미", "네이비", "베이지"],
    price: 145000,
    tags: ["부드러운 인상", "누진 가능"],
  },
  {
    id: "f-sqr-01",
    name: "카이 스퀘어",
    brand: "KAI",
    shape: "square",
    rim: "full",
    material: "TR-90",
    lensWidth: 52,
    bridge: 18,
    lensHeight: 38,
    temple: 145,
    totalWidth: 140,
    weightGram: 17,
    asianFit: true,
    adjustableNosePad: true,
    colors: ["매트 블랙", "카키", "버건디"],
    price: 98000,
    tags: ["가벼움", "도수 커버", "가성비"],
  },
  {
    id: "f-rnd-01",
    name: "루아 라운드",
    brand: "LUA",
    shape: "round",
    rim: "full",
    material: "메탈",
    lensWidth: 46,
    bridge: 22,
    lensHeight: 44,
    temple: 145,
    totalWidth: 132,
    weightGram: 15,
    asianFit: false,
    adjustableNosePad: true,
    colors: ["골드", "실버", "앤틱 브론즈"],
    price: 156000,
    tags: ["레트로", "코패드 조절"],
  },
  {
    id: "f-cat-01",
    name: "베라 캣아이",
    brand: "VERA",
    shape: "cat-eye",
    rim: "full",
    material: "아세테이트",
    lensWidth: 51,
    bridge: 17,
    lensHeight: 39,
    temple: 140,
    totalWidth: 137,
    weightGram: 21,
    asianFit: true,
    adjustableNosePad: false,
    colors: ["블랙", "와인", "크리스탈 핑크"],
    price: 168000,
    tags: ["또렷한 인상", "상단 강조"],
  },
  {
    id: "f-brw-01",
    name: "온 브로우라인",
    brand: "ON",
    shape: "browline",
    rim: "half",
    material: "콤비",
    lensWidth: 50,
    bridge: 20,
    lensHeight: 40,
    temple: 145,
    totalWidth: 139,
    weightGram: 19,
    asianFit: true,
    adjustableNosePad: true,
    colors: ["블랙 골드", "브라운 골드", "그레이 실버"],
    price: 174000,
    tags: ["상단 강조", "클래식"],
  },
  {
    id: "f-ovl-01",
    name: "시하 오벌",
    brand: "SIHA",
    shape: "oval",
    rim: "full",
    material: "티타늄",
    lensWidth: 49,
    bridge: 19,
    lensHeight: 37,
    temple: 140,
    totalWidth: 133,
    weightGram: 11,
    asianFit: true,
    adjustableNosePad: true,
    colors: ["샴페인 골드", "티탄 그레이", "화이트"],
    price: 219000,
    tags: ["초경량", "티타늄", "장시간 착용"],
  },
  {
    id: "f-rec-01",
    name: "노아 렉탱글",
    brand: "NOAH",
    shape: "rectangle",
    rim: "full",
    material: "TR-90",
    lensWidth: 54,
    bridge: 17,
    lensHeight: 35,
    temple: 148,
    totalWidth: 143,
    weightGram: 18,
    asianFit: true,
    adjustableNosePad: true,
    colors: ["매트 블랙", "그레이", "네이비"],
    price: 112000,
    tags: ["큰 얼굴", "가벼움"],
  },
  {
    id: "f-oct-01",
    name: "코르 옥타곤",
    brand: "KOR",
    shape: "octagon",
    rim: "full",
    material: "메탈",
    lensWidth: 47,
    bridge: 21,
    lensHeight: 41,
    temple: 145,
    totalWidth: 134,
    weightGram: 16,
    asianFit: false,
    adjustableNosePad: true,
    colors: ["골드", "블랙", "실버"],
    price: 149000,
    tags: ["개성", "코패드 조절"],
  },
  {
    id: "f-avi-01",
    name: "하늘 보잉",
    brand: "HANEUL",
    shape: "aviator",
    rim: "full",
    material: "메탈",
    lensWidth: 55,
    bridge: 16,
    lensHeight: 43,
    temple: 145,
    totalWidth: 142,
    weightGram: 20,
    asianFit: false,
    adjustableNosePad: true,
    colors: ["골드", "건메탈"],
    price: 162000,
    tags: ["큰 테", "코패드 조절"],
  },
  {
    id: "f-rim-01",
    name: "여백 무테",
    brand: "YEOBAEK",
    shape: "oval",
    rim: "rimless",
    material: "티타늄",
    lensWidth: 52,
    bridge: 19,
    lensHeight: 33,
    temple: 145,
    totalWidth: 138,
    weightGram: 9,
    asianFit: true,
    adjustableNosePad: true,
    colors: ["실버", "골드", "로즈"],
    price: 235000,
    tags: ["초경량", "안 쓴 듯", "저도수 권장"],
  },
  {
    id: "f-hlf-01",
    name: "담 하금테",
    brand: "DAM",
    shape: "square",
    rim: "half",
    material: "콤비",
    lensWidth: 51,
    bridge: 18,
    lensHeight: 36,
    temple: 145,
    totalWidth: 138,
    weightGram: 14,
    asianFit: true,
    adjustableNosePad: true,
    colors: ["블랙", "브라운", "실버"],
    price: 138000,
    tags: ["단정함", "가벼움"],
  },
  {
    id: "f-wel-02",
    name: "다온 웰링턴 스몰",
    brand: "DAON",
    shape: "wellington",
    rim: "full",
    material: "아세테이트",
    lensWidth: 46,
    bridge: 20,
    lensHeight: 40,
    temple: 138,
    totalWidth: 128,
    weightGram: 20,
    asianFit: true,
    adjustableNosePad: false,
    colors: ["블랙", "그린 데미"],
    price: 124000,
    tags: ["작은 얼굴", "고도수 유리"],
  },
  {
    id: "f-bos-02",
    name: "무이 보스턴 라지",
    brand: "MUI",
    shape: "boston",
    rim: "full",
    material: "아세테이트",
    lensWidth: 53,
    bridge: 21,
    lensHeight: 46,
    temple: 148,
    totalWidth: 145,
    weightGram: 27,
    asianFit: true,
    adjustableNosePad: false,
    colors: ["블랙", "하바나"],
    price: 152000,
    tags: ["큰 얼굴", "누진 가능"],
  },
];

export function findFrame(id: string): Frame | undefined {
  return FRAMES.find((f) => f.id === id);
}
